[build-system]
requires = [
    "setuptools",
    "wheel",
    "torch",
    "numpy",
]
build-backend = "setuptools.build_meta"

[project]
name = "gaussians2life"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    "markupsafe",
    "numpy",
    "nvidia-cudnn-cu11",
    "torch",
    "torchvision",
]

[tool.setuptools]
packages = ["gaussians2life"]